import {
  isPublicAssetKey,
  verifyAssetSignature,
} from "@/server/storage/asset-url-signing";
import { storage } from "@/server/storage";
import { NextRequest, NextResponse } from "next/server";

type RouteParams = { params: Promise<{ key: string[] }> };

/**
 * Serves files the app stores itself (STORAGE_PROVIDER=filesystem or database).
 *
 * - avatars and logos are public (same as a public bucket)
 * - everything else (screenshots) needs the `exp` + `sig` query params minted
 *   by `storage.getSignedUrl`, mirroring an S3 presigned GET.
 */
export async function GET(req: NextRequest, { params }: RouteParams) {
  const { key: segments } = await params;
  let key: string;
  try {
    key = segments.map(decodeURIComponent).join("/");
  } catch {
    return NextResponse.json({ error: "Bad request" }, { status: 400 });
  }
  if (!isWellFormedKey(key)) {
    return NextResponse.json({ error: "Bad request" }, { status: 400 });
  }

  if (!isPublicAssetKey(key)) {
    const exp = Number(req.nextUrl.searchParams.get("exp"));
    const sig = req.nextUrl.searchParams.get("sig") ?? "";
    if (!verifyAssetSignature(key, exp, sig)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
  }

  let object = null;
  try {
    object = storage.read ? await storage.read(key) : null;
  } catch (error) {
    console.error(`[assets] read failed (key=${key}):`, error);
  }
  if (!object) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  return new NextResponse(new Uint8Array(object.data), {
    headers: {
      "Content-Type": object.mimeType,
      "Content-Length": String(object.size),
      // Keys are unique per upload (timestamp / uuid), so long caching is safe.
      "Cache-Control": isPublicAssetKey(key)
        ? "public, max-age=31536000, immutable"
        : "private, max-age=3600",
      "X-Content-Type-Options": "nosniff",
    },
  });
}

/**
 * Keys are generated by the app ("prefix/id/uuid.ext"). Anything else – dot
 * segments, empty segments, backslashes, control characters – is rejected
 * before it reaches a storage backend.
 */
function isWellFormedKey(key: string): boolean {
  if (!key || key.length > 512) return false;
  // eslint-disable-next-line no-control-regex
  if (/[\\\u0000-\u001f]/.test(key)) return false;
  return key.split("/").every((segment) => segment !== "" && segment !== "." && segment !== "..");
}
